# Generated by Django 6.0.3 on 2026-03-25 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_can_post_in_connect_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resignation_date', models.DateField()),
                ('last_working_day', models.DateField()),
                ('stage', models.CharField(choices=[('notice_received', 'Notice received'), ('knowledge_transfer', 'Knowledge transfer'), ('clearance', 'Clearance'), ('alumni_conversion', 'Alumni conversion'), ('completed', 'Completed')], default='notice_received', max_length=32)),
                ('resignation_acknowledged', models.BooleanField(default=False)),
                ('knowledge_transfer_completed', models.BooleanField(default=False)),
                ('assets_returned', models.BooleanField(default=False)),
                ('access_review_completed', models.BooleanField(default=False)),
                ('alumni_transition_completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='exit_process', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_exit_processes', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_exit_processes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-updated_at', '-created_at'),
                'permissions': [('manage_exit_process', 'Can manage employee exit processes')],
            },
        ),
    ]
