# Generated by Django 6.0.3 on 2026-03-28 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_exitprocess"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmployeeSSOIdentitySnapshot",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("sso_user_id", models.CharField(blank=True, max_length=120)),
                ("email", models.EmailField(max_length=254)),
                ("full_name", models.CharField(blank=True, max_length=255)),
                ("employee_id", models.CharField(blank=True, max_length=120)),
                ("company", models.CharField(blank=True, max_length=120)),
                ("employment_type", models.CharField(blank=True, max_length=120)),
                ("raw_payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_sso_identity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("user__email",),
            },
        ),
    ]
