# Generated by Django 6.0.3 on 2026-03-25 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleshipMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('invited', 'Invited'), ('ship_placement', 'Ship placement'), ('active', 'Active'), ('paused_office_hours', 'Paused for office hours'), ('completed', 'Completed'), ('resigned', 'Resigned'), ('abandoned', 'Abandoned'), ('declined', 'Declined'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='invited', max_length=32)),
                ('occupies_global_slot', models.BooleanField(db_index=True, default=False)),
                ('paused_from_status', models.CharField(blank=True, max_length=32)),
                ('invitation_expires_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(blank=True, null=True)),
                ('total_turns', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inactive_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battleship_inactivity_flags', to=settings.AUTH_USER_MODEL)),
                ('invitee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battleship_invites_received', to=settings.AUTH_USER_MODEL)),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battleship_invites_sent', to=settings.AUTH_USER_MODEL)),
                ('loser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battleship_losses', to=settings.AUTH_USER_MODEL)),
                ('rematch_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rematches', to='battleship.battleshipmatch')),
                ('resigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battleship_resignations', to=settings.AUTH_USER_MODEL)),
                ('turn_owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battleship_turns', to=settings.AUTH_USER_MODEL)),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battleship_wins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BattleshipEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('invite_sent', 'Invite sent'), ('invite_accepted', 'Invite accepted'), ('invite_declined', 'Invite declined'), ('invite_expired', 'Invite expired'), ('invite_cancelled', 'Invite cancelled'), ('match_started', 'Match started'), ('match_paused', 'Match paused'), ('match_resumed', 'Match resumed'), ('ships_locked', 'Ships locked'), ('shot_fired', 'Shot fired'), ('match_completed', 'Match completed'), ('match_resigned', 'Match resigned'), ('match_abandoned', 'Match abandoned'), ('rematch_requested', 'Rematch requested')], max_length=32)),
                ('summary', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='battleship_events', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='battleship.battleshipmatch')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='BattleshipParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('challenger', 'Challenger'), ('opponent', 'Opponent')], max_length=16)),
                ('fleet_layout', models.JSONField(blank=True, default=list)),
                ('placement_ready', models.BooleanField(default=False)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='battleship.battleshipmatch')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battleship_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='BattleshipShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.PositiveSmallIntegerField()),
                ('col', models.PositiveSmallIntegerField()),
                ('result', models.CharField(choices=[('hit', 'Hit'), ('miss', 'Miss'), ('sunk', 'Sunk')], max_length=16)),
                ('ship_type', models.CharField(blank=True, max_length=24)),
                ('turn_number', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots', to='battleship.battleshipmatch')),
                ('shooter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battleship_shots_fired', to=settings.AUTH_USER_MODEL)),
                ('target_participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shots_received', to='battleship.battleshipparticipant')),
            ],
            options={
                'ordering': ('turn_number', 'created_at'),
            },
        ),
        migrations.AddConstraint(
            model_name='battleshipmatch',
            constraint=models.UniqueConstraint(condition=models.Q(('occupies_global_slot', True)), fields=('occupies_global_slot',), name='battleship_single_global_slot'),
        ),
        migrations.AddConstraint(
            model_name='battleshipparticipant',
            constraint=models.UniqueConstraint(fields=('match', 'user'), name='battleship_unique_participant_per_match'),
        ),
        migrations.AddConstraint(
            model_name='battleshipparticipant',
            constraint=models.UniqueConstraint(fields=('match', 'slot'), name='battleship_unique_slot_per_match'),
        ),
        migrations.AddConstraint(
            model_name='battleshipshot',
            constraint=models.UniqueConstraint(fields=('match', 'turn_number'), name='battleship_unique_turn_number_per_match'),
        ),
        migrations.AddConstraint(
            model_name='battleshipshot',
            constraint=models.UniqueConstraint(fields=('match', 'target_participant', 'row', 'col'), name='battleship_unique_target_cell_per_match'),
        ),
        migrations.AddConstraint(
            model_name='battleshipshot',
            constraint=models.CheckConstraint(condition=models.Q(('col__gte', 0), ('col__lt', 10), ('row__gte', 0), ('row__lt', 10)), name='battleship_shot_within_grid'),
        ),
    ]
