# Generated by Django 6.0.3 on 2026-03-23 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_analyticsevent_ip_address_analyticsevent_request_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton_key', models.CharField(default='primary', max_length=32, unique=True)),
                ('counter', models.PositiveIntegerField(default=1)),
                ('display_number', models.CharField(default='1.0000001', max_length=32)),
                ('commit_sha', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Build state',
                'verbose_name_plural': 'Build state',
            },
        ),
    ]
