# Generated by Django 6.0.3 on 2026-03-23 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directoryprofile',
            name='company_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='directoryprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directoryprofile',
            name='emergency_contact_number',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='directoryprofile',
            name='function_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='directoryprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
