def serialize_user(user):
    return {
        "id": user.id,
        "email": user.email,
        "name": user.full_name,
        "initials": user.initials,
        "title": user.title,
        "department": user.department,
        "location": user.location,
        "employee_code": user.employee_code,
        "phone_number": user.phone_number,
        "employment_status": user.employment_status,
        "is_active": user.is_active,
        "access_level": user.access_level,
        "is_staff": user.is_staff,
        "can_post_in_connect": user.can_post_in_connect,
        "is_directory_visible": user.is_directory_visible,
        "access_rights": {
            "can_employee": user.has_employee_access,
            "can_moderate": user.can_moderate_connect,
            "can_administer": user.can_administer_connect,
            "can_manage_access_rights": user.can_manage_access_rights,
            "can_post": user.can_create_connect_posts,
            "can_comment": user.can_comment_in_connect,
            "can_react": user.can_react_in_connect,
            "can_post_as_company": user.can_post_as_company,
        },
        "must_change_password": user.must_change_password,
        "password_change_required": user.password_change_required,
        "password_changed_at": user.password_changed_at.isoformat() if user.password_changed_at else None,
        "password_due_at": user.password_due_at.isoformat() if user.password_due_at else None,
        "password_days_until_expiry": user.password_days_until_expiry,
        "last_seen_at": user.last_seen_at.isoformat() if user.last_seen_at else None,
        "date_joined": user.date_joined.isoformat() if user.date_joined else None,
    }


def serialize_exit_process(process):
    return {
        "id": process.id,
        "employee": serialize_user(process.employee),
        "stage": process.stage,
        "resignation_date": process.resignation_date.isoformat() if process.resignation_date else None,
        "last_working_day": process.last_working_day.isoformat() if process.last_working_day else None,
        "resignation_acknowledged": process.resignation_acknowledged,
        "knowledge_transfer_completed": process.knowledge_transfer_completed,
        "assets_returned": process.assets_returned,
        "access_review_completed": process.access_review_completed,
        "alumni_transition_completed": process.alumni_transition_completed,
        "can_finalize": process.can_finalize,
        "notes": process.notes,
        "completed_at": process.completed_at.isoformat() if process.completed_at else None,
        "created_at": process.created_at.isoformat(),
        "updated_at": process.updated_at.isoformat(),
    }
