# Generated by Django 6.0.3 on 2026-03-23 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('body', models.TextField()),
                ('kind', models.CharField(choices=[('announcement', 'Announcement'), ('update', 'Update'), ('kudos', 'Kudos'), ('poll', 'Poll'), ('resource', 'Resource')], default='update', max_length=24)),
                ('visibility', models.CharField(choices=[('company', 'Company-wide'), ('department', 'Department'), ('leadership', 'Leadership')], default='company', max_length=24)),
                ('moderation_status', models.CharField(choices=[('draft', 'Draft'), ('pending_review', 'Pending review'), ('published', 'Published'), ('rejected', 'Rejected'), ('removed', 'Removed')], default='draft', max_length=24)),
                ('allow_comments', models.BooleanField(default=True)),
                ('pinned', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pinned', '-published_at', '-created_at'),
                'permissions': [('moderate_post', 'Can moderate posts'), ('publish_post', 'Can publish posts')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('moderation_status', models.CharField(choices=[('published', 'Published'), ('pending_review', 'Pending review'), ('rejected', 'Rejected'), ('removed', 'Removed')], default='published', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='feed.post')),
            ],
            options={
                'ordering': ('created_at',),
                'permissions': [('moderate_comment', 'Can moderate comments')],
            },
        ),
    ]
